sudo: false
language: node_js
node_js:
  - 14
cache: yarn

install:
  - yarn install --non-interactive

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  - provider: s3
    access_key_id: $AWS_ID # this references the encrypted $var you gave Travis
    secret_access_key: $AWS_SECRET_KEY # this references the encrypted $var you gave Travis
    bucket: cul-s3-dlst-travis-rosehallproject-prod
    region: us-west-2
    skip_cleanup: true
    local_dir: dist
    on:
      branch: main
    verbose: true
