name: CI
on:
  push:
    branches:
      - main

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile

  lints:
    name: Lints
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn test

  build:
    name: Build App
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install_dependencies, test, build]
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.DLST_SERV_DEPLOY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DLST_SERV_DEPLOY_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Deploying to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ secrets.REPO_BUCKET_NAME }}
          bucket-region: "us-west-2"
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: "*/*,**"
    
  # check-secret:
  #   name: "Check Secret"
  #   runs-on: ubuntu-latest
  #   outputs:
  #     my-key: ${{ steps.my-key-outputs.defined }}
  #   steps:
  #     - id: my-key
  #       if: "${{ env.MY_KEY != '' }}"
  #       run: echo "::set-output name=defined::true"
  #       env: 
  #         MY_KEY: ${{ secrets.AWS}}
